### ISSUE TITLE
Negotiation spec fields

### ISSUE THREAD

**Issue by carterharrison** [XYOracleNetwork/spec-coreobjectmodel-tex#3]
Type up the negotiation bit fields currently seen [here](https://github.com/XYOracleNetwork/sdk-core-kotlin/blob/master/src/main/java/network/xyo/sdkcorekotlin/network/XyoProcedureCatalogue.kt) and [here](https://github.com/XYOracleNetwork/sdk-core-nodejs/blob/4a52ab0878f9b0d0641165b231e2576b897d2b4d/src/network/xyo-catalogue-item.ts#L12).

**Comment by maryannxy** [comment]
@carterharrison @ryanxyo Has this been completed?
